apiVersion: v1
data:
  PING_IDENTITY_ACCEPT_EULA: "YES"
  SERVER_PROFILE_PATH: baseline/pingaccess
  SERVER_PROFILE_URL: https://www.github.com/jacenb/pingidentity-server-profiles.git
  PING_IDENTITY_PASSWORD: "2SideBand"
  PING_IDENTITY_K8S_NAMESPACE: ${PING_IDENTITY_K8S_NAMESPACE}
  PA_LOG_LEVEL: "DEBUG"
  TLS: "TLSv1.2, TLSv1.3"
  CIPHER: "TLS_ECDHE_ECDSA_AES256_GCM_SHA384,TLS_ECDHE_ECDSA_AES128_GCM_SHA256,TLS_ECDHE_ECDSA_CHACHA20_POLY1305,TLS_ECDHE_RSA_CHACHA20_POLY1305,TLS_DHE_RSA_AES256_GCM_SHA384,TLS_DHE_RSA_AES256_CCM,TLS_DHE_RSA_AES128_GCM_SHA256,TLS_DHE_RSA_AES128_CCM,TLS_DHE_RSA_CHACHA20_POLY1305,TLS_DHE_RSA_WITH_AES_128_CBC_SHA"
kind: ConfigMap
metadata:
  labels:
    role: pingaccess
  name: pingaccess-environment-variables